### ISSUE TITLE
Plugin is not available in AMOS for translation

### ISSUE THREAD

**Issue by germanvaleroelizondo** [elearning-ostfalia/moodle-qtype_proforma#8]
Hi.
This plugin is not available for translation in AMOS.

Most likely there is a coding error with string concatenation.

Please see https://docs.moodle.org/404/en/Translating_plugins#Plugins_with_coding_errors 

I think lines 95 to 99 in lang/en/qtype_proforma.php might be the problem, but I am not a PHP programmer, I am a mere translator.

Thanks in advance

**Comment by KBorm** [comment]
Thank you for the info. The string resources have been updated so that the problem should now be fixed.

**Comment by germanvaleroelizondo** [comment]
Thanks, BUT... strings still NOT available for translation.

There might still be other issues.

Line 225-226 looks suspicious (string concatenation) to me (but I am not a PHP programmer):

$string['regexpfromgrader_desc'] = 'To display the compiler messages, the compiler output is parsed using a regular expression. ' .
        'Normally the regular expression should be used by the grader. In case of an error, however, the regular expression of the plugin can be used.';

**Comment by KBorm** [comment]
Oh sorry, I missed that out... should be ok now.

**Comment by germanvaleroelizondo** [comment]
Translations are now available in AMOS :)
I will add a Mexican spanish translation soon.
Thanks a lot.
